export const AUTH_ACTION_TYPES = {
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_ERROR: 'SIGNIN_ERROR',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_ERROR: 'SIGNOUT_ERROR'
}